_common/shippable/Adapter.js
tests/organization-owner/github/accountIntegrations/1.2.integrations_addIntegration.js

https://github.com/Shippable/bat/issues/161

add gitLab accountIntegration

---

tests/organization-owner/github/3-integrations/1.2.addIntegration.js

https://github.com/Shippable/bat/issues/166
https://github.com/Shippable/bat/issues/161

Adds rest of the accountIntegrations

---

tests/organization-owner/github/3-integrations/1.2.addIntegration.js

Revert "add shippableadapter"

---

tests/organization-owner/github/3-integrations/1.2.addIntegration.js
tests/organization-owner/github/3-integrations/1.2.getIntegrations.js

https://github.com/Shippable/bat/issues/160

Adds edit account integration test cases for all masterInts

---

_common/shippable/Adapter.js
package.json
tests/organization-owner/github/4-accountCards/1.2.addNewCard.js

https://github.com/Shippable/bat/issues/163

Adds account cards test suites

---

tests/organization-owner/github/5-subscriptions/1.2.technical-email-edit.js

https://github.com/Shippable/bat/issues/164

Adds testSuite for technical email in subscriptionSettings options

---

_common/shippable/Adapter.js
tests/organization-owner/github/5-subscriptions/1.2.4.resetSubscription.js

https://github.com/Shippable/bat/issues/164

Adds testSuite for Reset subscription in subscriptionSettings options

---

_common/shippable/Adapter.js

Revert "add string type response"

---

_common/shippable/Adapter.js

Revert "add string response"

---

_common/shippable/Adapter.js

Revert "check bag.body"

---

tests/organization-owner/github/5-projects/1.2.3 ClearcacheProject.js

https://github.com/Shippable/bat/issues/293

Adding clear cache file for project setting

---

_common/shippable/Adapter.js
tests/organization-owner/github/5-projects/1.2.4.ResetAproject.js

https://github.com/Shippable/bat/issues/292

Add ResetAProject file for project settings

---

tests/organization-owner/github/5-projects/1.2.9.RunsConfig.ConsolidateReports.js

https://github.com/Shippable/bat/issues/306

automate consolidate reports

---

tests/organization-owner/github/6-integrations/1.2.addIntegration.js

https://github.com/Shippable/pm/issues/7837

change systemIntegrationId of gitlab

---

tests/organization-owner/github/6-integrations/1.2.addIntegration.js
tests/organization-owner/github/6-integrations/1.2.getIntegrations.js

https://github.com/Shippable/pm/issues/7837

change masterIntegration Fields for gitlab

---

_common/shippable/Adapter.js
tests/organization-owner/github/5-projects/1.2.10.ProjectsDashBoard.js

https://github.com/Shippable/bat/issues/322

projects dashboard API tests

---

_common/shippable/Adapter.js
tests/organization-owner/github/5-projects/1.2.11.Home.js

https://github.com/Shippable/bat/issues/347

adds testCases for home dashboard

---

package.json
tests/testTokenExchange.js

https://github.com/Shippable/bat/issues/352

fixes jshint errors in testTokenExchange.js

---

tests/organization-owner/github/5-projects/1.2.12.RunsConsole.js

initializes the shippable adapter in the iterator

---

tests/organization-owner/github/5-projects/1.2.09.SubscriptionsDashboard.js

removes an extra done()

---

tests/organization-owner/github/5-projects/1.2.12.RunsConsole.js

loads the nconf

---

tests/organization-owner/github/5-projects/1.2.09.SubscriptionsDashboard.js
tests/organization-owner/github/5-projects/1.2.10.SubscriptionsHistory.js

sets the runId in the subscriptionHistory

---

tests/organization-owner/github/5-projects/1.2.12.RunsConsole.js

removes the done()

---

tests/getAccounts.js

https://github.com/Shippable/bat/issues/352

fixes jshint errors in getAccounts

---

tests/organization-owner/github/1-accounts/1.2.aa_setUp.js

https://github.com/Shippable/bat/issues/352

fixes jshint in accounts setup

---

tests/organization-owner/github/1-accounts/1.2.accounts_editEmail.js

https://github.com/Shippable/bat/issues/352

fixes jshint errors in accouts editEmail

---

tests/organization-owner/github/5-projects/1.2.08.ProjectHistory.js

https://github.com/Shippable/pm/issues/8063

wait until ur triggered build is completed

---

_common/shippable/Adapter.js
package.json
tests/organization-owner/github/5-projects/1.2.08.ProjectHistory.js

https://github.com/Shippable/bat/issues/406

add getJobStatesMap testCase

---

_common/shippable/Adapter.js

https://github.com/Shippable/pm/issues/7239
I have tested running test cases after changing the adapter.

update adapter to treat no response as a connectionError

---

tests/organization-owner/github/6-subscriptionNodes/1.2.05.NodeSettings.js

reset will throw 400 if node is in processing state or idle

disable reset if node is in processing or idle

---

tests/organization-owner/github/4-subscriptions/1.2.9.JobModalCtrl.js
tests/organization-owner/github/4-subscriptions/1.2.91.JobConsoleCtrl.js

https://github.com/Shippable/pm/issues/7239
Adding checks for:
```
387 passing (2m)
3 failing
1) 1.2 - Job Modal Job Modal Controller get Builds By resourceId:
Uncaught TypeError: Cannot read property 'id' of undefined
at tests/organization-owner/github/4-subscriptions/1.2.9.JobModalCtrl.js:105:44
at _common/shippable/Adapter.js:1237:9
at node_modules/async/dist/async.js:3694:9
at node_modules/async/dist/async.js:359:16
at replenish (node_modules/async/dist/async.js:876:25)
at iterateeCallback (node_modules/async/dist/async.js:866:17)
at node_modules/async/dist/async.js:843:16
at node_modules/async/dist/async.js:3691:13
at apply (node_modules/async/dist/async.js:21:25)
at node_modules/async/dist/async.js:56:12
at _parseBody (_common/shippable/Adapter.js:1384:10)
at …
```

add proper checks

---

tests/organization-owner/github/4-subscriptions/1.2.1.technical-email-edit.js
tests/organization-owner/github/4-subscriptions/1.2.2.billing-email-edit.js
tests/organization-owner/github/4-subscriptions/1.2.3.resetSubscription.js
tests/organization-owner/github/4-subscriptions/1.2.4.Encrypt.js
tests/organization-owner/github/4-subscriptions/1.2.5.AddResource.js
tests/organization-owner/github/4-subscriptions/1.2.6.ResourceModal.js
tests/organization-owner/github/4-subscriptions/1.2.7.ParamsModal.js
tests/organization-owner/github/4-subscriptions/1.2.8.pipelinesCtrl.js
tests/organization-owner/github/4-subscriptions/1.2.9.JobModalCtrl.js
tests/organization-owner/github/4-subscriptions/1.2.91.JobConsoleCtrl.js
tests/organization-owner/github/4-subscriptions/1.2.92.JobTraceCtrl.js
tests/organization-owner/github/4-subscriptions/1.2.93.DeleteResource.js

https://github.com/Shippable/bat/issues/429
Adding Checks for: 
```
2017-03-15T11:38:33.055Z - warn: PUT call to https://rcapi.shippable.com/subscriptions/ returned status 404 with error 404
2017-03-15T11:38:33.056Z - error: Unable to parse bag.body Cannot PUT /subscriptions/
SyntaxError: Unexpected token C
at Object.parse (native)
at _parseBody (/build/IN/bat_repo/gitRepo/_common/shippable/Adapter.js:1353:31)
at /build/IN/bat_repo/gitRepo/node_modules/async/dist/async.js:3686:9
at replenish (/build/IN/bat_repo/gitRepo/node_modules/async/dist/async.js:881:17)
at iterateeCallback (/build/IN/bat_repo/gitRepo/node_modules/async/dist/async.js:866:17)
at /build/IN/bat_repo/gitRepo/node_modules/async/dist/async.js:843:16
at /build/IN/bat_repo/gitRepo/node_modules/async/dist/async.js:3691:13
at …
```

standardize 4-subscriptions testcases

---

tests/organization-owner/github/5-projects/1.2.01.EnableAProject.js
tests/organization-owner/github/5-projects/1.2.02.PauseAProject.js
tests/organization-owner/github/5-projects/1.2.03.ClearcacheProject.js
tests/organization-owner/github/5-projects/1.2.04.Encrypt.js
tests/organization-owner/github/5-projects/1.2.05.ResetAproject.js
tests/organization-owner/github/5-projects/1.2.06.RunsConfig.js
tests/organization-owner/github/5-projects/1.2.07.ProjectsDashBoard.js
tests/organization-owner/github/5-projects/1.2.08.ProjectHistory.js
tests/organization-owner/github/5-projects/1.2.09.SubscriptionsDashboard.js
tests/organization-owner/github/5-projects/1.2.10.SubscriptionsHistory.js
tests/organization-owner/github/5-projects/1.2.11.Home.js
tests/organization-owner/github/5-projects/1.2.12.RunsConsole.js
tests/organization-owner/github/5-projects/1.2.13.RunTestReports.js
tests/organization-owner/github/5-projects/1.2.14.RunsScript.js
tests/organization-owner/github/5-projects/1.2.15.RunsCoverage.js
tests/organization-owner/github/5-projects/1.2.16.DisableProject.js
tests/organization-owner/github/5-projects/1.2.17.select-systemMachineImages.js

https://github.com/Shippable/bat/issues/429
locally verified for projects: 
```
Enable Project
1.2 - Enable Project
✓ Organization-Owner-github-getSubscription
✓ Get Projects
✓ Enable Project (5866ms)
Should run after above test suites
✓ Creating Github Issue if test cases failed
Pause Project
1.2 - Pause a Project
✓ Pause Project (70ms)
✓ Resume Project (66ms)
Should run after above test suites
✓ Creating Github Issue if test cases failed
Clear Cache
1.2 - Clear cache
✓ Clear Cache
Should run after above test suites
✓ Creating Github Issue if test cases failed
1.2 - Project settings - encrypt and decrypt
Encrypt and Decrypt
✓ Organization-Owner-github-getSubscription
✓ Enter encrypt value with alphabets and encrypt (50ms)
✓ Enter encrypt value with numbers and encrypt (51ms)
✓ Enter …
```

standardize 5-projects test cases

---

_common/shippable/Adapter.js

Revert "Adds back warn logs"

---

tests/organization-owner/github/4-subscriptions/1.2.5.AddResource.js
tests/organization-owner/github/7-integrations/1.2.addIntegration.js

https://github.com/Shippable/bat/issues/443

fetch account integrations for correct type

---

tests/organization-owner/github/6-subscriptionNodes/1.2.02.AddNewNode.js
tests/organization-owner/github/6-subscriptionNodes/1.2.05.NodeSettings.js

https://github.com/Shippable/bat/issues/446

delete node if it is not in processing state

---

tests/organization-owner/github/6-subscriptionNodes/1.2.05.NodeSettings.js

https://github.com/Shippable/bat/issues/446

updates checkIfClusterNodeProcessing

---

tests/organization-owner/github/6-subscriptionNodes/1.2.05.NodeSettings.js

https://github.com/Shippable/bat/issues/446

adds retry limit to checkIfClusterNodeProcessing

---

_common/shippable/Adapter.js

show response body in case of error

---

tests/testTokenExchange.js

https://github.com/Shippable/bat/issues/446
this adds retries, in case bvt is unable to connect to api during postAuth, due to swarm errors.

retry postAuth in case of 500 series errors

---

tests/organization-owner/github/2-apiTokens/1.2.apiTokens_addToken.js

wait until account is synced to post tokens

---

tests/organization-owner/github/2-apiTokens/1.2.apiTokens_addToken.js

https://github.com/Shippable/bat/issues/457
Stop sync micro service before merging this PR

waiting for sync to start & end before posting tokens
